# Generated by Django 2.0.3 on 2020-04-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_auto_20191212_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ENV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('env', models.TextField(default='', null=True)),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Index.ProjectInfo')),
            ],
            options={
                'verbose_name': '驱动py文件',
                'db_table': 'env',
            },
        ),
        migrations.AddField(
            model_name='moduleinfo',
            name='IsCreatetest',
            field=models.CharField(default='1', max_length=1, verbose_name='是否已批量生成用例'),
        ),
        migrations.AlterField(
            model_name='testcaseinfo',
            name='type',
            field=models.IntegerField(default=1, verbose_name='test/config/api'),
        ),
    ]
