# Generated by Django 2.0.3 on 2020-04-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0005_testreports_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
